### ISSUE TITLE
Check if the microserviceName is correctly added

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#219]

**Comment by MathieuAA** [comment]
ping @davidweianibone

**Comment by davidweianibone** [comment]
Hi Mathieu,

I have created my entities using UMLDesigner and jhipster-uml.
Seems like all the json files that were created are missing the microservice name

Sure

##### **JHipster Version(s)**

```
/Users/david/git/AniBoneMcrService
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "AniBoneMcrService",
    "packageName": "com.anibone",
    "packageFolder": "com/anibone",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "SECRET KEY",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "serviceDiscoveryType": "eureka"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

AbUser.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "projects",
      "otherEntityName": "project",
      "otherEntityRelationshipName": "abUser"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "addresss",
      "otherEntityName": "address",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "abUser"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "personalZones",
      "otherEntityName": "personalZone",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "abUser"
    }
  ],
  "fields": [
    {
      "fieldName": "mail",
      "fieldType": "String"
    },
    {
      "fieldName": "endStatusDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "pass",
      "fieldType": "String"
    },
    {
      "fieldName": "cellPhone",
      "fieldType": "String"
    },
    {
      "fieldName": "userName",
      "fieldType": "String"
    },
    {
      "fieldName": "firstName",
      "fieldType": "String"
    },
    {
      "fieldName": "homePhone",
      "fieldType": "String"
    },
    {
      "fieldName": "status",
      "fieldType": "UserStatusEnum",
      "fieldValues": "NEW,ACTIVE,CANCELED,SUSPENDED"
    },
    {
      "fieldName": "startStatusDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "lastName",
      "fieldType": "String"
    },
    {
      "fieldName": "userRole",
      "fieldType": "UserRole",
      "fieldValues": "ADMIN,CONSUMER,GUEST,BUSINESS"
    }
  ],
  "changelogDate": "20161015161335",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "ab_user"
}
```

Address.json

```yaml
{
  "fluentMethods": true,
  "relationships": [],
  "fields": [
    {
      "fieldName": "city",
      "fieldType": "String"
    },
    {
      "fieldName": "street",
      "fieldType": "String"
    },
    {
      "fieldName": "houseNum",
      "fieldType": "String"
    },
    {
      "fieldName": "zip",
      "fieldType": "String"
    },
    {
      "fieldName": "country",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161321",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "address"
}
```

Article.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "personalZone",
      "otherEntityName": "personalZone",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "abUsers",
      "otherEntityName": "abUser",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "article"
    },
    {
      "relationshipName": "articleCategory",
      "otherEntityName": "articleCategory",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "issueDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "title",
      "fieldType": "String"
    },
    {
      "fieldName": "description",
      "fieldType": "String"
    },
    {
      "fieldName": "article",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161325",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "article"
}
```

ArticleCategory.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "articles",
      "otherEntityName": "article",
      "otherEntityRelationshipName": "articleCategory"
    }
  ],
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "photo",
      "fieldType": "String"
    },
    {
      "fieldName": "description",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161330",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "article_category"
}
```

AssetLocation.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "addresss",
      "otherEntityName": "address",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "assetLocation"
    }
  ],
  "fields": [
    {
      "fieldName": "plotNum",
      "fieldType": "Integer"
    },
    {
      "fieldName": "blockNum",
      "fieldType": "Integer"
    },
    {
      "fieldName": "propertySize",
      "fieldType": "Integer"
    },
    {
      "fieldName": "propertyNum",
      "fieldType": "Integer"
    },
    {
      "fieldName": "issueId",
      "fieldType": "Integer"
    }
  ],
  "changelogDate": "20161015161329",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "asset_location"
}
```

AssetSpecs.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "assetLocations",
      "otherEntityName": "assetLocation",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "assetSpecs"
    }
  ],
  "fields": [
    {
      "fieldName": "homeArea",
      "fieldType": "String"
    },
    {
      "fieldName": "numOfFloors",
      "fieldType": "Integer"
    },
    {
      "fieldName": "landPurchaseMethod",
      "fieldType": "LandPurchaseMethodEnum",
      "fieldValues": "GOVERMENT,PRIVATE,NONE"
    },
    {
      "fieldName": "constructionStandard",
      "fieldType": "ValueStandardEnum",
      "fieldValues": "HEIGH,MEDIUM,LOW"
    },
    {
      "fieldName": "constructionShelterStandard",
      "fieldType": "ValueStandardEnum",
      "fieldValues": "HEIGH,MEDIUM,LOW"
    },
    {
      "fieldName": "propertyValue",
      "fieldType": "Integer"
    },
    {
      "fieldName": "hasShelter",
      "fieldType": "Boolean"
    },
    {
      "fieldName": "shleterArea",
      "fieldType": "Integer"
    },
    {
      "fieldName": "totalBudget",
      "fieldType": "Integer"
    }
  ],
  "changelogDate": "20161015161326",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "asset_specs"
}
```

Business.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "addresss",
      "otherEntityName": "address",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "business"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "ranks",
      "otherEntityName": "rank",
      "otherEntityRelationshipName": "business"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "regions",
      "otherEntityName": "region",
      "otherEntityRelationshipName": "business"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "abDocs",
      "otherEntityName": "doc",
      "otherEntityRelationshipName": "business"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "abUsers",
      "otherEntityName": "abUser",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "business"
    },
    {
      "relationshipName": "personalZone",
      "otherEntityName": "personalZone",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipName": "businessCategory",
      "otherEntityName": "businessCategory",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "workPhone",
      "fieldType": "String"
    },
    {
      "fieldName": "fax",
      "fieldType": "String"
    },
    {
      "fieldName": "workMail",
      "fieldType": "String"
    },
    {
      "fieldName": "siteUrl",
      "fieldType": "String"
    },
    {
      "fieldName": "description",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161323",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "business"
}
```

BusinessCategory.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "businesss",
      "otherEntityName": "business",
      "otherEntityRelationshipName": "businessCategory"
    },
    {
      "relationshipName": "businessCategory",
      "otherEntityName": "businessCategory",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "businessCategorys",
      "otherEntityName": "businessCategory",
      "otherEntityRelationshipName": "businessCategory"
    }
  ],
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "icon",
      "fieldType": "String"
    },
    {
      "fieldName": "color",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161331",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "business_category"
}
```

Doc.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "task",
      "otherEntityName": "task",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipName": "business",
      "otherEntityName": "business",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "description",
      "fieldType": "String"
    },
    {
      "fieldName": "updateDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "isLogo",
      "fieldType": "Boolean"
    }
  ],
  "changelogDate": "20161015161334",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "doc"
}
```

Finance.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "project",
      "otherEntityName": "project",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "fundSource",
      "fieldType": "FundSourceEnum",
      "fieldValues": "SELF,MORGAGE,LOAN,OTHER"
    },
    {
      "fieldName": "sum",
      "fieldType": "Integer"
    },
    {
      "fieldName": "months",
      "fieldType": "Integer"
    },
    {
      "fieldName": "intrest",
      "fieldType": "Integer"
    }
  ],
  "changelogDate": "20161015161327",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "finance"
}
```

Payment.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "subTask",
      "otherEntityName": "subTask",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "sumPayed",
      "fieldType": "Integer"
    },
    {
      "fieldName": "paymentDate",
      "fieldType": "LocalDate"
    }
  ],
  "changelogDate": "20161015161328",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "payment"
}
```

PersonalZone.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "businesss",
      "otherEntityName": "business",
      "otherEntityRelationshipName": "personalZone"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "articles",
      "otherEntityName": "article",
      "otherEntityRelationshipName": "personalZone"
    }
  ],
  "fields": [],
  "changelogDate": "20161015161324",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "personal_zone"
}
```

Project.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "tasks",
      "otherEntityName": "task",
      "otherEntityRelationshipName": "project"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "projectDetailss",
      "otherEntityName": "assetSpecs",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "project"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "finances",
      "otherEntityName": "finance",
      "otherEntityRelationshipName": "project"
    },
    {
      "relationshipName": "abUser",
      "otherEntityName": "abUser",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "projectType",
      "fieldType": "ProjectTypeEnum",
      "fieldValues": "CONSTRUCTION,RENOVATION,FROM_CONTRACTOR"
    },
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "startStatusDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "endStatusDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "siUnits",
      "fieldType": "SiUnitsEnum",
      "fieldValues": "INTERNATIONAL,IMPERIAL"
    },
    {
      "fieldName": "contructMethod",
      "fieldType": "ContructMethodEnum",
      "fieldValues": "KEY,MULTI,COMBINE,SELF"
    },
    {
      "fieldName": "listView",
      "fieldType": "Boolean"
    },
    {
      "fieldName": "photo",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161319",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "project"
}
```

Rank.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "business",
      "otherEntityName": "business",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "abUsers",
      "otherEntityName": "abUser",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "rank"
    }
  ],
  "fields": [
    {
      "fieldName": "scor",
      "fieldType": "Integer"
    },
    {
      "fieldName": "rankDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "feedback",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161332",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "rank"
}
```

Region.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "business",
      "otherEntityName": "business",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipName": "region",
      "otherEntityName": "region",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "regions",
      "otherEntityName": "region",
      "otherEntityRelationshipName": "region"
    }
  ],
  "fields": [
    {
      "fieldName": "regionName",
      "fieldType": "String"
    }
  ],
  "changelogDate": "20161015161333",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "region"
}
```

SubTask.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "task",
      "otherEntityName": "task",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "payments",
      "otherEntityName": "payment",
      "otherEntityRelationshipName": "subTask"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "businesss",
      "otherEntityName": "business",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "subTask"
    },
    {
      "relationshipType": "one-to-one",
      "relationshipValidateRules": "required",
      "relationshipName": "articles",
      "otherEntityName": "article",
      "otherEntityField": "id",
      "ownerSide": true,
      "otherEntityRelationshipName": "subTask"
    }
  ],
  "fields": [
    {
      "fieldName": "subTaskStatus",
      "fieldType": "TaskStatusEnum",
      "fieldValues": "COMPLETED,INPROGRESS,NEW,NOT_ASSIGNED"
    },
    {
      "fieldName": "lastVisitDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "lastUpdateDate",
      "fieldType": "LocalDate"
    },
    {
      "fieldName": "subTaskType",
      "fieldType": "SubTaskTypeEnum",
      "fieldValues": "MANDATORY,OPTIONAL,PROPERTY,CUSTOMIZE"
    },
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "estimateSystemCost",
      "fieldType": "Integer"
    },
    {
      "fieldName": "userCost",
      "fieldType": "Integer"
    },
    {
      "fieldName": "note",
      "fieldType": "String"
    },
    {
      "fieldName": "tip",
      "fieldType": "String"
    },
    {
      "fieldName": "indx",
      "fieldType": "Integer"
    }
  ],
  "changelogDate": "20161015161322",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "sub_task"
}
```

Task.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "project",
      "otherEntityName": "project",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "subTasks",
      "otherEntityName": "subTask",
      "otherEntityRelationshipName": "task"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "abDocs",
      "otherEntityName": "doc",
      "otherEntityRelationshipName": "task"
    }
  ],
  "fields": [
    {
      "fieldName": "taskStatus",
      "fieldType": "TaskStatusEnum",
      "fieldValues": "COMPLETED,INPROGRESS,NEW,NOT_ASSIGNED"
    },
    {
      "fieldName": "name",
      "fieldType": "String"
    },
    {
      "fieldName": "valueStandard",
      "fieldType": "ValueStandardEnum",
      "fieldValues": "HEIGH,MEDIUM,LOW"
    },
    {
      "fieldName": "icon",
      "fieldType": "String"
    },
    {
      "fieldName": "color",
      "fieldType": "String"
    },
    {
      "fieldName": "indx",
      "fieldType": "Integer"
    },
    {
      "fieldName": "listView",
      "fieldType": "Boolean"
    }
  ],
  "changelogDate": "20161015161320",
  "dto": "mapstruct",
  "pagination": "no",
  "service": "no",
  "entityTableName": "task"
}
```

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.10.0

node: v6.9.1

npm: 3.10.8

bower: 1.7.9

gulp:
[22:08:45] CLI version 1.2.2

yeoman: 1.8.5

Docker version 1.12.1, build 6f9534c

docker-compose version 1.8.0, build f3628c7
